# Generated by Django 4.0.3 on 2022-04-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_post_image_alter_post_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='photo',
        ),
    ]
